<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNXVYqRW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNXVYqRW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNXVYqRW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNXVYqRW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNXVYqRW\App_KernelDevDebugContainer([
    'container.build_hash' => 'NXVYqRW',
    'container.build_id' => 'b7218a76',
    'container.build_time' => 1587626856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNXVYqRW');
