<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDkIVwNy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDkIVwNy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDkIVwNy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDkIVwNy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDkIVwNy\App_KernelDevDebugContainer([
    'container.build_hash' => 'DkIVwNy',
    'container.build_id' => '79d5a38b',
    'container.build_time' => 1587755695,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDkIVwNy');
