<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWZy3luz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWZy3luz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWZy3luz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWZy3luz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWZy3luz\App_KernelDevDebugContainer([
    'container.build_hash' => 'WZy3luz',
    'container.build_id' => 'da573268',
    'container.build_time' => 1587566609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWZy3luz');
